
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;


/**
 * Display Appointments
 * @author fscovino
 */
public class AppointmentPanel extends javax.swing.JPanel {

    MainFrame parent;
    Controller controller;
    CellRenderer cellRender;
    
    public AppointmentPanel(MainFrame parent) {
        initComponents();
        this.parent = parent;
        this.controller = new Controller();
        cellRender = new CellRenderer();
        setDataTable();
        setTotalTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainAppointment = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlFilter = new javax.swing.JPanel();
        lblLookFor = new javax.swing.JLabel();
        txtLookFor = new javax.swing.JTextField();
        lblInField = new javax.swing.JLabel();
        cboInField = new javax.swing.JComboBox<>();
        lblDateFrom = new javax.swing.JLabel();
        dtcFrom = new com.toedter.calendar.JDateChooser();
        lblDateTo = new javax.swing.JLabel();
        dtcTo = new com.toedter.calendar.JDateChooser();
        lblOnDateFields = new javax.swing.JLabel();
        cboDateFields = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnClearSearch = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        spnlDataTable = new javax.swing.JScrollPane();
        tblDataTable = new javax.swing.JTable();
        pnlTotals = new javax.swing.JPanel();
        spnlTotals = new javax.swing.JScrollPane();
        tblTotals = new javax.swing.JTable();
        pnlFooter = new javax.swing.JPanel();
        btnExitPanel = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 960));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pnlMainAppointment.setPreferredSize(new java.awt.Dimension(1280, 960));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 153, 153));
        lblTitle.setText("Appointments");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFilter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLookFor.setLabelFor(txtLookFor);
        lblLookFor.setText("Look for");

        txtLookFor.setToolTipText("");
        txtLookFor.setMinimumSize(new java.awt.Dimension(30, 26));
        txtLookFor.setPreferredSize(new java.awt.Dimension(175, 24));

        lblInField.setLabelFor(cboInField);
        lblInField.setText("In");

        cboInField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Claim ID", "Claim Status", "Patient Name", "Appointment Type", "Appt. Status", "Service", "Appt. Date", "Start Time", "End Time", "Duration", "Units", "Minutes / Qty", "Codes", "Place of Service", "Primary Payer", "Therapist Name", "Charges", "Therapist Charges", "Gross Profit", "Profit %" }));
        cboInField.setPreferredSize(new java.awt.Dimension(120, 24));

        lblDateFrom.setText("From");

        dtcFrom.setDateFormatString("MMM dd,yyyy");
        dtcFrom.setMaxSelectableDate(new java.util.Date(253370786509000L));
        dtcFrom.setMinSelectableDate(new java.util.Date(-62135747891000L));
        dtcFrom.setPreferredSize(new java.awt.Dimension(91, 24));

        lblDateTo.setText("To");

        dtcTo.setDateFormatString("MMM dd,yyyy");
        dtcTo.setPreferredSize(new java.awt.Dimension(91, 24));

        lblOnDateFields.setLabelFor(cboDateFields);
        lblOnDateFields.setText("On");

        cboDateFields.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appt. Date", "Ins. Paid Date", "Pat. Paid Date" }));
        cboDateFields.setPreferredSize(new java.awt.Dimension(170, 24));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filter.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(120, 33));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClearSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/broom.png"))); // NOI18N
        btnClearSearch.setText("Clear (0)");
        btnClearSearch.setPreferredSize(new java.awt.Dimension(120, 33));
        btnClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFilterLayout = new javax.swing.GroupLayout(pnlFilter);
        pnlFilter.setLayout(pnlFilterLayout);
        pnlFilterLayout.setHorizontalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLookFor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLookFor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboInField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDateFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtcFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDateTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtcTo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOnDateFields)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboDateFields, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        pnlFilterLayout.setVerticalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dtcFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateTo)
                    .addComponent(dtcTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOnDateFields)
                    .addComponent(cboDateFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLookFor)
                    .addComponent(txtLookFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInField)
                    .addComponent(cboInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateFrom))
                .addContainerGap())
        );

        spnlDataTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spnlDataTable.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblDataTable.setAutoCreateRowSorter(true);
        tblDataTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblDataTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDataTable.setNextFocusableComponent(btnExport);
        tblDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblDataTableMouseReleased(evt);
            }
        });
        spnlDataTable.setViewportView(tblDataTable);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnlDataTable)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnlDataTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        spnlTotals.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnlTotals.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tblTotals.setAutoCreateRowSorter(true);
        tblTotals.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblTotals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tblTotals.setColumnSelectionAllowed(true);
        tblTotals.setNextFocusableComponent(btnExport);
        tblTotals.setRowHeight(20);
        tblTotals.setRowSelectionAllowed(false);
        tblTotals.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        spnlTotals.setViewportView(tblTotals);

        javax.swing.GroupLayout pnlTotalsLayout = new javax.swing.GroupLayout(pnlTotals);
        pnlTotals.setLayout(pnlTotalsLayout);
        pnlTotalsLayout.setHorizontalGroup(
            pnlTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnlTotals)
        );
        pnlTotalsLayout.setVerticalGroup(
            pnlTotalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalsLayout.createSequentialGroup()
                .addComponent(spnlTotals, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnExitPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnExitPanel.setText("Close");
        btnExitPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitPanelActionPerformed(evt);
            }
        });

        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/csv.png"))); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExitPanel)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainAppointmentLayout = new javax.swing.GroupLayout(pnlMainAppointment);
        pnlMainAppointment.setLayout(pnlMainAppointmentLayout);
        pnlMainAppointmentLayout.setHorizontalGroup(
            pnlMainAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTotals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainAppointmentLayout.setVerticalGroup(
            pnlMainAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainAppointmentLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTotals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlMainAppointment);
    }// </editor-fold>//GEN-END:initComponents

    // Close Appointment Panel amd back to Home Page
    private void btnExitPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitPanelActionPerformed
        setVisible(false);
        parent.goBackHome();
    }//GEN-LAST:event_btnExitPanelActionPerformed

    // Clear all filter parameters and set model back to all rows
    private void btnClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSearchActionPerformed
        // Clear all filter fields
        txtLookFor.setText("");
        txtLookFor.grabFocus();
        dtcFrom.setDate(null);
        dtcTo.setDate(null);
        // Clear all parameters from list
        int filtersQty = controller.clearSearchParamAppointments();
        btnClearSearch.setText("Clear (" + filtersQty + ")");
        controller.filterTable(tblDataTable, "", 0, null, null, 0);
        setTotalTable();
    }//GEN-LAST:event_btnClearSearchActionPerformed

    // Filter the table with the parameters selected on the filter fields
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        int filtersQty;
        filtersQty = controller.filterTable(tblDataTable, txtLookFor.getText(), cboInField.getSelectedIndex(), dtcFrom.getDate(), dtcTo.getDate(), cboDateFields.getSelectedIndex());
        btnClearSearch.setText("Clear (" + filtersQty + ")");
        txtLookFor.grabFocus();
        txtLookFor.selectAll();
        setTotalTable();
    }//GEN-LAST:event_btnSearchActionPerformed

    // Generate totals for selected rows everytime a row is selected
    private void tblDataTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataTableMouseReleased
        setTotalTable();
    }//GEN-LAST:event_tblDataTableMouseReleased

    // Export Selected data to CSV file
    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        int success = controller.exportDataToCsv(tblDataTable, "Appointments");
        if (success == 1){
            JOptionPane.showMessageDialog(null, "Data Exported Successfully", "Data Exported", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Data Could not be Exported", "Data Exported", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnExportActionPerformed

    // Get table data and populate the table
    private void setDataTable(){
        tblDataTable.setModel(controller.getAppointmentModel());
        // Set initial column width
        for (int i = 0; i < tblDataTable.getColumnCount(); i++){
            tblDataTable.getColumnModel().getColumn(i).setPreferredWidth(125);
        }
        // Set the format for columns to display date and price properly
        for (int i = 0; i < tblDataTable.getColumnCount(); i++){
            if ((i != 2) && (i != 14) && (i != 15)) {
                tblDataTable.getColumnModel().getColumn(i).setCellRenderer(cellRender);
            }
        }
    }
    
// Generate totals for selected rows everytime a row is selected
    private void setTotalTable(){
        TableModel model = controller.getAppointmentTotalsModel(tblDataTable);
        tblTotals.setModel(model);
        
        // Set the format for columns to display date and price properly
        for (int i = 0; i < tblTotals.getColumnCount(); i++){
            tblTotals.getColumnModel().getColumn(i).setCellRenderer(cellRender);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearSearch;
    private javax.swing.JButton btnExitPanel;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboDateFields;
    private javax.swing.JComboBox<String> cboInField;
    private com.toedter.calendar.JDateChooser dtcFrom;
    private com.toedter.calendar.JDateChooser dtcTo;
    private javax.swing.JLabel lblDateFrom;
    private javax.swing.JLabel lblDateTo;
    private javax.swing.JLabel lblInField;
    private javax.swing.JLabel lblLookFor;
    private javax.swing.JLabel lblOnDateFields;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlFilter;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlMainAppointment;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlTotals;
    private javax.swing.JScrollPane spnlDataTable;
    private javax.swing.JScrollPane spnlTotals;
    private javax.swing.JTable tblDataTable;
    private javax.swing.JTable tblTotals;
    private javax.swing.JTextField txtLookFor;
    // End of variables declaration//GEN-END:variables
}
