
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Fuzion Viewer
 * Import .csv files from Fuzion Clinic and display relevant information
 * February 20, 2020
 * @author Francisco Scovino
 */
public class MainFrame extends javax.swing.JFrame {
    
    AppointmentPanel appointmentPanel;
    

    public MainFrame() {
        initComponents();
        appointmentPanel = new AppointmentPanel(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainPanel = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        mnbMain = new javax.swing.JMenuBar();
        mnuProgram = new javax.swing.JMenu();
        mniImport = new javax.swing.JMenuItem();
        mniSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        mnuModules = new javax.swing.JMenu();
        mniAppointments = new javax.swing.JMenuItem();
        mniTherapists = new javax.swing.JMenuItem();
        mniPatients = new javax.swing.JMenuItem();
        mniInsurances = new javax.swing.JMenuItem();
        mniSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniCodes = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        mniReport1 = new javax.swing.JMenuItem();
        mniReport2 = new javax.swing.JMenuItem();
        mniReport3 = new javax.swing.JMenuItem();
        mnuNotifications = new javax.swing.JMenu();
        mniOpenNotifications = new javax.swing.JMenuItem();
        mniRefreshNotifications = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fuzion Viewer");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));
        setLocationByPlatform(true);
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 768));

        pnlMainPanel.setLayout(new java.awt.BorderLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_300.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addContainerGap(748, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addContainerGap())
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addContainerGap())
        );

        pnlMainPanel.add(pnlLogo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMainPanel, java.awt.BorderLayout.CENTER);

        mnuProgram.setText("Program");

        mniImport.setText("Import Data");
        mnuProgram.add(mniImport);
        mnuProgram.add(mniSeparator1);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuProgram.add(mniExit);

        mnbMain.add(mnuProgram);

        mnuModules.setText("Modules");

        mniAppointments.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mniAppointments.setText("Appointments");
        mniAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAppointmentsActionPerformed(evt);
            }
        });
        mnuModules.add(mniAppointments);

        mniTherapists.setText("Therapists");
        mnuModules.add(mniTherapists);

        mniPatients.setText("Patients");
        mnuModules.add(mniPatients);

        mniInsurances.setText("Insurances");
        mnuModules.add(mniInsurances);
        mnuModules.add(mniSeparator2);

        mniCodes.setText("Codes");
        mnuModules.add(mniCodes);

        mnbMain.add(mnuModules);

        mnuReports.setText("Reports");

        mniReport1.setText("Report 1");
        mnuReports.add(mniReport1);

        mniReport2.setText("Report 2");
        mnuReports.add(mniReport2);

        mniReport3.setText("Report 3");
        mnuReports.add(mniReport3);

        mnbMain.add(mnuReports);

        mnuNotifications.setText("Notifications");

        mniOpenNotifications.setText("Open Notifications");
        mnuNotifications.add(mniOpenNotifications);

        mniRefreshNotifications.setText("Refresh");
        mnuNotifications.add(mniRefreshNotifications);

        mnbMain.add(mnuNotifications);

        setJMenuBar(mnbMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Go back to home - set logo panel visible
    public void goBackHome(){
        pnlMainPanel.removeAll();
        pnlMainPanel.add(pnlLogo);
        pnlMainPanel.revalidate();
    }
    
    // Open Appointment panel
    private void mniAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAppointmentsActionPerformed
        pnlMainPanel.removeAll();
        pnlMainPanel.add(appointmentPanel);
        appointmentPanel.setVisible(true);
        pnlMainPanel.revalidate();
    }//GEN-LAST:event_mniAppointmentsActionPerformed

    // Shutdown Application
    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    
    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        
        /* Set the Application look and fell */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, "<MAINFRAME>main():\n" + ex.getMessage(), "Look and Feel Exception", JOptionPane.INFORMATION_MESSAGE);
        }

        /* Create and display the main form on a thread */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenuBar mnbMain;
    private javax.swing.JMenuItem mniAppointments;
    private javax.swing.JMenuItem mniCodes;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniImport;
    private javax.swing.JMenuItem mniInsurances;
    private javax.swing.JMenuItem mniOpenNotifications;
    private javax.swing.JMenuItem mniPatients;
    private javax.swing.JMenuItem mniRefreshNotifications;
    private javax.swing.JMenuItem mniReport1;
    private javax.swing.JMenuItem mniReport2;
    private javax.swing.JMenuItem mniReport3;
    private javax.swing.JPopupMenu.Separator mniSeparator1;
    private javax.swing.JPopupMenu.Separator mniSeparator2;
    private javax.swing.JMenuItem mniTherapists;
    private javax.swing.JMenu mnuModules;
    private javax.swing.JMenu mnuNotifications;
    private javax.swing.JMenu mnuProgram;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlMainPanel;
    // End of variables declaration//GEN-END:variables
}
