package fv.Views;

import fv.controllers.Controller;

public class InsurancePanel extends javax.swing.JPanel {

    MainFrame parent;
    Controller controller;
    

    public InsurancePanel(MainFrame parent, Controller controller) {
        initComponents();
        this.parent = parent;
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainInsurance = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        tpnlMainInsurance = new javax.swing.JTabbedPane();
        pnlInsuranceList = new javax.swing.JPanel();
        pnlFilterInsurance = new javax.swing.JPanel();
        lblLookForInsurance = new javax.swing.JLabel();
        txtLookForInsurance = new javax.swing.JTextField();
        btnClearSearchInsurance = new javax.swing.JButton();
        pnlTableListAll = new javax.swing.JPanel();
        spnlDataTable = new javax.swing.JScrollPane();
        tblDataTable = new javax.swing.JTable();
        pnlInsuranceDetail = new javax.swing.JPanel();
        spnlInsuranceDetail = new javax.swing.JScrollPane();
        pnlInsuranceDetailInner = new javax.swing.JPanel();
        lblInsurance = new javax.swing.JLabel();
        txtInsuranceName = new javax.swing.JTextField();
        lblInsuranceID = new javax.swing.JLabel();
        txtInsuranceID = new javax.swing.JTextField();
        lblGroupName = new javax.swing.JLabel();
        txtGroupName = new javax.swing.JTextField();
        lblGroupNumber = new javax.swing.JLabel();
        txtGroupNumber = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblAltPhoneNumber = new javax.swing.JLabel();
        txtAltPhoneNumber = new javax.swing.JTextField();
        lblFaxNumber = new javax.swing.JLabel();
        txtFaxNumber = new javax.swing.JTextField();
        lblEmailAddress = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        cboState = new javax.swing.JComboBox<>();
        lblZipCode = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        lblHireDate = new javax.swing.JLabel();
        dtcHireDate = new com.toedter.calendar.JDateChooser();
        lblPosition = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        lblProfLicenseNumber = new javax.swing.JLabel();
        txtProfLicenseNumber = new javax.swing.JTextField();
        lblProfLicenseExpDate = new javax.swing.JLabel();
        dtcProfLicenseExpDate = new com.toedter.calendar.JDateChooser();
        lblNPINumber = new javax.swing.JLabel();
        txtNPINumber = new javax.swing.JTextField();
        lblMedicaidNumber = new javax.swing.JLabel();
        txtMedicaidNumber = new javax.swing.JTextField();
        lblCAQHNumber = new javax.swing.JLabel();
        txtCAQHNumber = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        pnlInsuranceServices = new javax.swing.JPanel();
        pnlFilterService = new javax.swing.JPanel();
        lblLookForService = new javax.swing.JLabel();
        txtLookForService = new javax.swing.JTextField();
        btnClearSearchService = new javax.swing.JButton();
        lblInsuranceName = new javax.swing.JLabel();
        chbSeePreviousRates = new javax.swing.JCheckBox();
        pnlServices = new javax.swing.JPanel();
        pnlTableServices = new javax.swing.JScrollPane();
        tbtServices = new javax.swing.JTable();
        pnlNotes = new javax.swing.JPanel();
        lblNotes = new javax.swing.JLabel();
        spnlNotes = new javax.swing.JScrollPane();
        txpNotes = new javax.swing.JTextPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 153, 153));
        lblTitle.setText("Insurances");

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_add.png"))); // NOI18N
        btnCreate.setText("New");

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_edit.png"))); // NOI18N
        btnUpdate.setText("Save");

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_delete.png"))); // NOI18N
        btnDelete.setText("Delete");

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
        btnPrint.setText("Print");

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrint)
                        .addComponent(btnDelete)
                        .addComponent(btnUpdate)
                        .addComponent(btnCreate)
                        .addComponent(btnClose))
                    .addComponent(lblTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpnlMainInsurance.setMinimumSize(new java.awt.Dimension(0, 0));
        tpnlMainInsurance.setPreferredSize(new java.awt.Dimension(0, 0));

        pnlFilterInsurance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlFilterInsurance.setPreferredSize(new java.awt.Dimension(460, 59));

        lblLookForInsurance.setText("Look For:");

        btnClearSearchInsurance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/broom.png"))); // NOI18N
        btnClearSearchInsurance.setText("Clear");

        javax.swing.GroupLayout pnlFilterInsuranceLayout = new javax.swing.GroupLayout(pnlFilterInsurance);
        pnlFilterInsurance.setLayout(pnlFilterInsuranceLayout);
        pnlFilterInsuranceLayout.setHorizontalGroup(
            pnlFilterInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterInsuranceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLookForInsurance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLookForInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearSearchInsurance)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        pnlFilterInsuranceLayout.setVerticalGroup(
            pnlFilterInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilterInsuranceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFilterInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnClearSearchInsurance)
                    .addComponent(txtLookForInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLookForInsurance))
                .addContainerGap())
        );

        tblDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDataTable.setFillsViewportHeight(true);
        tblDataTable.setMinimumSize(new java.awt.Dimension(0, 0));
        tblDataTable.setName(""); // NOI18N
        tblDataTable.setPreferredSize(new java.awt.Dimension(0, 0));
        spnlDataTable.setViewportView(tblDataTable);

        javax.swing.GroupLayout pnlTableListAllLayout = new javax.swing.GroupLayout(pnlTableListAll);
        pnlTableListAll.setLayout(pnlTableListAllLayout);
        pnlTableListAllLayout.setHorizontalGroup(
            pnlTableListAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnlDataTable)
        );
        pnlTableListAllLayout.setVerticalGroup(
            pnlTableListAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableListAllLayout.createSequentialGroup()
                .addComponent(spnlDataTable, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pnlInsuranceListLayout = new javax.swing.GroupLayout(pnlInsuranceList);
        pnlInsuranceList.setLayout(pnlInsuranceListLayout);
        pnlInsuranceListLayout.setHorizontalGroup(
            pnlInsuranceListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFilterInsurance, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
            .addComponent(pnlTableListAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlInsuranceListLayout.setVerticalGroup(
            pnlInsuranceListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsuranceListLayout.createSequentialGroup()
                .addComponent(pnlFilterInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTableListAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpnlMainInsurance.addTab("Insurances List", pnlInsuranceList);

        spnlInsuranceDetail.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        spnlInsuranceDetail.setPreferredSize(new java.awt.Dimension(907, 768));

        lblInsurance.setText("Insurance Name");

        lblInsuranceID.setText("Insurance ID");

        lblGroupName.setText("Group Name");

        lblGroupNumber.setText("Group Number");

        lblPhoneNumber.setText("Phone Number");

        lblAltPhoneNumber.setText("Alternative Phone Number");

        lblFaxNumber.setText("Fax Number");

        lblEmailAddress.setText("Email Address");

        lblAddress.setText("Address");

        lblCity.setText("City");

        lblState.setText("State");

        cboState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming" }));

        lblZipCode.setText("Zip Code");

        lblHireDate.setText("Hire Date");

        lblPosition.setText("Contract / Employee - Position");

        lblProfLicenseNumber.setText("Prof License");

        lblProfLicenseExpDate.setText("License Expiration Date");

        lblNPINumber.setText("NPI Number");

        lblMedicaidNumber.setText("Medicaid Number");

        lblCAQHNumber.setText("CAQH Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Section 1: Application");

        jCheckBox1.setText("Application for Employment");

        jCheckBox2.setText("Resume");

        jCheckBox3.setText("Reference 1");

        jCheckBox4.setText("Reference 2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Section 2");

        jCheckBox5.setText("Job Description");

        jCheckBox6.setText("Independent Subcontractor Agreement");

        jCheckBox7.setText("Orientation Checklist");

        jCheckBox8.setText("W4 / W9");

        javax.swing.GroupLayout pnlInsuranceDetailInnerLayout = new javax.swing.GroupLayout(pnlInsuranceDetailInner);
        pnlInsuranceDetailInner.setLayout(pnlInsuranceDetailInnerLayout);
        pnlInsuranceDetailInnerLayout.setHorizontalGroup(
            pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                        .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInsuranceName)
                            .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInsurance)
                                    .addComponent(lblPhoneNumber))
                                .addGap(0, 122, Short.MAX_VALUE))
                            .addComponent(txtPhoneNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInsuranceID)
                            .addComponent(txtInsuranceID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAltPhoneNumber)
                            .addComponent(txtAltPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGroupName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(lblGroupName)
                                .addComponent(txtFaxNumber))
                            .addComponent(lblFaxNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmailAddress)
                            .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGroupNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(lblGroupNumber)
                                .addComponent(txtEmailAddress))))
                    .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1)
                            .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(dtcHireDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                                        .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAddress)
                                            .addComponent(lblHireDate))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCity)
                                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPosition))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblState)
                                    .addComponent(txtProfLicenseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(lblProfLicenseNumber)
                                    .addComponent(cboState, 0, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(lblZipCode)
                                    .addComponent(lblProfLicenseExpDate))))
                        .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                            .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNPINumber)
                                .addComponent(txtNPINumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMedicaidNumber)
                                .addComponent(txtMedicaidNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCAQHNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCAQHNumber)))
                        .addComponent(dtcProfLicenseExpDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                            .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jCheckBox1))
                            .addGap(205, 205, 205)
                            .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox5)
                                .addComponent(jLabel6)
                                .addComponent(jCheckBox6)
                                .addComponent(jCheckBox7)
                                .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                                    .addComponent(jCheckBox8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        pnlInsuranceDetailInnerLayout.setVerticalGroup(
            pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                        .addComponent(lblInsuranceID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInsuranceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                        .addComponent(lblInsurance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInsuranceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                        .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGroupName)
                            .addComponent(lblGroupNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGroupNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAltPhoneNumber)
                    .addComponent(lblPhoneNumber)
                    .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFaxNumber)
                        .addComponent(lblEmailAddress)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                        .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                                .addComponent(lblCity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                                .addComponent(lblAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                                    .addComponent(lblZipCode)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                                    .addComponent(lblState)
                                    .addGap(26, 26, 26))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                                .addComponent(lblProfLicenseNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProfLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPosition)
                                    .addComponent(lblHireDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtcHireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                        .addComponent(lblProfLicenseExpDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtcProfLicenseExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                        .addComponent(lblCAQHNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCAQHNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                        .addComponent(lblMedicaidNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMedicaidNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInsuranceDetailInnerLayout.createSequentialGroup()
                        .addComponent(lblNPINumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNPINumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInsuranceDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox4)
                        .addComponent(jCheckBox8))
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(624, Short.MAX_VALUE))
        );

        spnlInsuranceDetail.setViewportView(pnlInsuranceDetailInner);

        javax.swing.GroupLayout pnlInsuranceDetailLayout = new javax.swing.GroupLayout(pnlInsuranceDetail);
        pnlInsuranceDetail.setLayout(pnlInsuranceDetailLayout);
        pnlInsuranceDetailLayout.setHorizontalGroup(
            pnlInsuranceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnlInsuranceDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        pnlInsuranceDetailLayout.setVerticalGroup(
            pnlInsuranceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnlInsuranceDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        tpnlMainInsurance.addTab("Details", pnlInsuranceDetail);

        pnlFilterService.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLookForService.setText("Look For:");

        btnClearSearchService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/broom.png"))); // NOI18N
        btnClearSearchService.setText("Clear");

        lblInsuranceName.setText("Insurance Name");

        chbSeePreviousRates.setText("See Previous Rates");

        javax.swing.GroupLayout pnlFilterServiceLayout = new javax.swing.GroupLayout(pnlFilterService);
        pnlFilterService.setLayout(pnlFilterServiceLayout);
        pnlFilterServiceLayout.setHorizontalGroup(
            pnlFilterServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLookForService)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLookForService, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearSearchService)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbSeePreviousRates)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInsuranceName)
                .addContainerGap())
        );
        pnlFilterServiceLayout.setVerticalGroup(
            pnlFilterServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilterServiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFilterServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLookForService)
                    .addComponent(txtLookForService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearSearchService)
                    .addComponent(lblInsuranceName)
                    .addComponent(chbSeePreviousRates))
                .addGap(17, 17, 17))
        );

        pnlTableServices.setPreferredSize(new java.awt.Dimension(0, 0));

        tbtServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbtServices.setFillsViewportHeight(true);
        tbtServices.setMaximumSize(new java.awt.Dimension(0, 0));
        tbtServices.setMinimumSize(new java.awt.Dimension(0, 0));
        tbtServices.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlTableServices.setViewportView(tbtServices);

        javax.swing.GroupLayout pnlServicesLayout = new javax.swing.GroupLayout(pnlServices);
        pnlServices.setLayout(pnlServicesLayout);
        pnlServicesLayout.setHorizontalGroup(
            pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTableServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlServicesLayout.setVerticalGroup(
            pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTableServices, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        lblNotes.setText("Notes");

        spnlNotes.setViewportView(txpNotes);

        javax.swing.GroupLayout pnlNotesLayout = new javax.swing.GroupLayout(pnlNotes);
        pnlNotes.setLayout(pnlNotesLayout);
        pnlNotesLayout.setHorizontalGroup(
            pnlNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
            .addGroup(pnlNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlNotesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spnlNotes)
                        .addComponent(lblNotes))
                    .addContainerGap()))
        );
        pnlNotesLayout.setVerticalGroup(
            pnlNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
            .addGroup(pnlNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlNotesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblNotes)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(spnlNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlInsuranceServicesLayout = new javax.swing.GroupLayout(pnlInsuranceServices);
        pnlInsuranceServices.setLayout(pnlInsuranceServicesLayout);
        pnlInsuranceServicesLayout.setHorizontalGroup(
            pnlInsuranceServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFilterService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlInsuranceServicesLayout.setVerticalGroup(
            pnlInsuranceServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsuranceServicesLayout.createSequentialGroup()
                .addComponent(pnlFilterService, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpnlMainInsurance.addTab("Services", pnlInsuranceServices);

        javax.swing.GroupLayout pnlMainInsuranceLayout = new javax.swing.GroupLayout(pnlMainInsurance);
        pnlMainInsurance.setLayout(pnlMainInsuranceLayout);
        pnlMainInsuranceLayout.setHorizontalGroup(
            pnlMainInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpnlMainInsurance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainInsuranceLayout.setVerticalGroup(
            pnlMainInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInsuranceLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnlMainInsurance, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
        );

        tpnlMainInsurance.getAccessibleContext().setAccessibleName("Insurances List");
        tpnlMainInsurance.getAccessibleContext().setAccessibleDescription("");

        add(pnlMainInsurance);
    }// </editor-fold>//GEN-END:initComponents

    // Hide Therapist Panel and go to Home Panel
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        parent.goBackHome();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearSearchInsurance;
    private javax.swing.JButton btnClearSearchService;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboState;
    private javax.swing.JCheckBox chbSeePreviousRates;
    private com.toedter.calendar.JDateChooser dtcHireDate;
    private com.toedter.calendar.JDateChooser dtcProfLicenseExpDate;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAltPhoneNumber;
    private javax.swing.JLabel lblCAQHNumber;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblGroupName;
    private javax.swing.JLabel lblGroupNumber;
    private javax.swing.JLabel lblHireDate;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JLabel lblInsuranceID;
    private javax.swing.JLabel lblInsuranceName;
    private javax.swing.JLabel lblLookForInsurance;
    private javax.swing.JLabel lblLookForService;
    private javax.swing.JLabel lblMedicaidNumber;
    private javax.swing.JLabel lblNPINumber;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblProfLicenseExpDate;
    private javax.swing.JLabel lblProfLicenseNumber;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JPanel pnlFilterInsurance;
    private javax.swing.JPanel pnlFilterService;
    private javax.swing.JPanel pnlInsuranceDetail;
    private javax.swing.JPanel pnlInsuranceDetailInner;
    private javax.swing.JPanel pnlInsuranceList;
    private javax.swing.JPanel pnlInsuranceServices;
    private javax.swing.JPanel pnlMainInsurance;
    private javax.swing.JPanel pnlNotes;
    private javax.swing.JPanel pnlServices;
    private javax.swing.JPanel pnlTableListAll;
    private javax.swing.JScrollPane pnlTableServices;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane spnlDataTable;
    private javax.swing.JScrollPane spnlInsuranceDetail;
    private javax.swing.JScrollPane spnlNotes;
    private javax.swing.JTable tblDataTable;
    private javax.swing.JTable tbtServices;
    private javax.swing.JTabbedPane tpnlMainInsurance;
    private javax.swing.JTextPane txpNotes;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAltPhoneNumber;
    private javax.swing.JTextField txtCAQHNumber;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtGroupName;
    private javax.swing.JTextField txtGroupNumber;
    private javax.swing.JTextField txtInsuranceID;
    private javax.swing.JTextField txtInsuranceName;
    private javax.swing.JTextField txtLookForInsurance;
    private javax.swing.JTextField txtLookForService;
    private javax.swing.JTextField txtMedicaidNumber;
    private javax.swing.JTextField txtNPINumber;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtProfLicenseNumber;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
