package fv.Views;

import fv.controllers.Controller;
import fv.models.Settings;
import java.io.File;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class SettingsPanel extends javax.swing.JPanel {

    MainFrame parent;
    Controller controller;
    Settings settings;
    
    /**
     * Creates new form TherapistPanel
     * @param parent
     * @param controller
     * @throws java.sql.SQLException
     */
    public SettingsPanel(MainFrame parent, Controller controller) throws SQLException {
        initComponents();
        this.parent = parent;
        this.controller = controller;
        this.settings = controller.getApplicationSettings();
        setFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainTherapist = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        tpnlMainTherapist = new javax.swing.JTabbedPane();
        pnlTherapistDetail = new javax.swing.JPanel();
        spnlTherapistDetail = new javax.swing.JScrollPane();
        pnlTherapistDetailInner = new javax.swing.JPanel();
        lblExternalTables = new javax.swing.JLabel();
        lblAppointmentPath = new javax.swing.JLabel();
        txtAppointmentPath = new javax.swing.JTextField();
        btnAppointmentPath = new javax.swing.JButton();
        lblAdjudicationsPath = new javax.swing.JLabel();
        txtAdjudicationsPath = new javax.swing.JTextField();
        btnAdjudicationsPath = new javax.swing.JButton();
        lblTransactionsPath = new javax.swing.JLabel();
        txtTransactionsPath = new javax.swing.JTextField();
        btnTransactionsPath = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblReportPathMain = new javax.swing.JLabel();
        lblReportPath = new javax.swing.JLabel();
        txtReportPath = new javax.swing.JTextField();
        btnReportPath = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblNotificationsMain = new javax.swing.JLabel();
        lblTherapistNotifications = new javax.swing.JLabel();
        chbTherapistHireDate = new javax.swing.JCheckBox();
        txtTherapistHireDate = new javax.swing.JTextField();
        lblTherapistHireDateDaysBefore = new javax.swing.JLabel();
        chbTherapistProfLic = new javax.swing.JCheckBox();
        txtTherapistProfLic = new javax.swing.JTextField();
        lblTherapistProfLicDaysBefore = new javax.swing.JLabel();
        chbTherapistDriverLic = new javax.swing.JCheckBox();
        txtTherapistDriverLic = new javax.swing.JTextField();
        lblTherapistDriverLicDaysBefore = new javax.swing.JLabel();
        chbW4W9 = new javax.swing.JCheckBox();
        txtW4W9 = new javax.swing.JTextField();
        lblW4W9DaysBefore = new javax.swing.JLabel();
        chbPhysicalExam = new javax.swing.JCheckBox();
        txtPhysicalExam = new javax.swing.JTextField();
        lblPhysicalExamDaysBefore = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        chbPatientBirthday = new javax.swing.JCheckBox();
        txtPatientBirthday = new javax.swing.JTextField();
        lblPatientBirthdayDaysBefore = new javax.swing.JLabel();
        lblPatientsNotifications = new javax.swing.JLabel();
        chbPatientInsExp = new javax.swing.JCheckBox();
        txtPatientInsExp = new javax.swing.JTextField();
        lblPatientInsExpDaysBefore = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 153, 153));
        lblTitle.setText("Settings");

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_edit.png"))); // NOI18N
        btnUpdate.setText("Save");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 618, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate)
                        .addComponent(btnClose))
                    .addComponent(lblTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpnlMainTherapist.setMinimumSize(new java.awt.Dimension(0, 0));
        tpnlMainTherapist.setPreferredSize(new java.awt.Dimension(0, 0));

        spnlTherapistDetail.setPreferredSize(new java.awt.Dimension(0, 0));

        lblExternalTables.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblExternalTables.setText("External Tables");

        lblAppointmentPath.setText("Appointments");

        btnAppointmentPath.setText("Browse");
        btnAppointmentPath.setActionCommand("Appointments");
        btnAppointmentPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentPathActionPerformed(evt);
            }
        });

        lblAdjudicationsPath.setText("Adjudications");

        btnAdjudicationsPath.setText("Browse");
        btnAdjudicationsPath.setActionCommand("Adjudications");
        btnAdjudicationsPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjudicationsPathActionPerformed(evt);
            }
        });

        lblTransactionsPath.setText("Transactions");

        btnTransactionsPath.setText("Browse");
        btnTransactionsPath.setActionCommand("Transactions");
        btnTransactionsPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionsPathActionPerformed(evt);
            }
        });

        lblReportPathMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReportPathMain.setText("Reports Path");

        lblReportPath.setText("Path");

        btnReportPath.setText("Browse");
        btnReportPath.setActionCommand("Reports");
        btnReportPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportPathActionPerformed(evt);
            }
        });

        lblNotificationsMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNotificationsMain.setText("Notifications");

        lblTherapistNotifications.setText("Therapists");

        chbTherapistHireDate.setText("Hire Date");

        lblTherapistHireDateDaysBefore.setText("Days Before");

        chbTherapistProfLic.setText("Professional License");

        lblTherapistProfLicDaysBefore.setText("Days Before");

        chbTherapistDriverLic.setText("Driver License");

        lblTherapistDriverLicDaysBefore.setText("Days Before");

        chbW4W9.setText("W4 / W9");

        lblW4W9DaysBefore.setText("Days Before");

        chbPhysicalExam.setText("Physical Exam");

        lblPhysicalExamDaysBefore.setText("Days Before");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        chbPatientBirthday.setText("Birthday");

        lblPatientBirthdayDaysBefore.setText("Days Before");

        lblPatientsNotifications.setText("Patients");

        chbPatientInsExp.setText("Insurance Expiration");

        lblPatientInsExpDaysBefore.setText("Days Before");

        javax.swing.GroupLayout pnlTherapistDetailInnerLayout = new javax.swing.GroupLayout(pnlTherapistDetailInner);
        pnlTherapistDetailInner.setLayout(pnlTherapistDetailInnerLayout);
        pnlTherapistDetailInnerLayout.setHorizontalGroup(
            pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotificationsMain)
                    .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTherapistDetailInnerLayout.createSequentialGroup()
                                    .addComponent(chbPhysicalExam)
                                    .addGap(30, 30, 30)
                                    .addComponent(txtPhysicalExam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblPhysicalExamDaysBefore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTherapistDetailInnerLayout.createSequentialGroup()
                                    .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                                            .addComponent(chbW4W9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtW4W9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTherapistDetailInnerLayout.createSequentialGroup()
                                            .addComponent(chbTherapistDriverLic)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTherapistDriverLic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chbTherapistHireDate)
                                            .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtTherapistHireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                                                    .addComponent(chbTherapistProfLic)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtTherapistProfLic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblTherapistHireDateDaysBefore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTherapistProfLicDaysBefore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTherapistDriverLicDaysBefore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblW4W9DaysBefore))))
                            .addComponent(lblTherapistNotifications))
                        .addGap(101, 101, 101)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPatientsNotifications)
                            .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                                .addComponent(chbPatientInsExp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPatientInsExp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPatientInsExpDaysBefore))
                            .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                                .addComponent(chbPatientBirthday)
                                .addGap(61, 61, 61)
                                .addComponent(txtPatientBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPatientBirthdayDaysBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                            .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTherapistDetailInnerLayout.createSequentialGroup()
                                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAppointmentPath)
                                            .addComponent(lblAdjudicationsPath))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAdjudicationsPath, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                                            .addComponent(txtAppointmentPath)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTherapistDetailInnerLayout.createSequentialGroup()
                                        .addComponent(lblTransactionsPath)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTransactionsPath, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)))
                                .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                                    .addComponent(lblReportPath)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtReportPath, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAdjudicationsPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTransactionsPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAppointmentPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReportPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator2)
                        .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                            .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblExternalTables)
                                .addComponent(lblReportPathMain))
                            .addGap(314, 314, 314))))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        pnlTherapistDetailInnerLayout.setVerticalGroup(
            pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExternalTables)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppointmentPath)
                    .addComponent(txtAppointmentPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAppointmentPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdjudicationsPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdjudicationsPath)
                    .addComponent(lblAdjudicationsPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTransactionsPath)
                    .addComponent(txtTransactionsPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransactionsPath))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblReportPathMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReportPath)
                    .addComponent(txtReportPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportPath))
                .addGap(32, 32, 32)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNotificationsMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                        .addComponent(lblTherapistNotifications)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbTherapistHireDate)
                            .addComponent(txtTherapistHireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTherapistHireDateDaysBefore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbTherapistProfLic)
                            .addComponent(txtTherapistProfLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTherapistProfLicDaysBefore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbTherapistDriverLic)
                            .addComponent(txtTherapistDriverLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTherapistDriverLicDaysBefore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbW4W9)
                            .addComponent(txtW4W9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblW4W9DaysBefore))
                        .addGap(6, 6, 6)
                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbPhysicalExam)
                            .addComponent(txtPhysicalExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhysicalExamDaysBefore)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTherapistDetailInnerLayout.createSequentialGroup()
                        .addComponent(lblPatientsNotifications)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbPatientBirthday)
                            .addComponent(txtPatientBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientBirthdayDaysBefore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTherapistDetailInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbPatientInsExp)
                            .addComponent(txtPatientInsExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientInsExpDaysBefore))))
                .addContainerGap(659, Short.MAX_VALUE))
        );

        spnlTherapistDetail.setViewportView(pnlTherapistDetailInner);

        javax.swing.GroupLayout pnlTherapistDetailLayout = new javax.swing.GroupLayout(pnlTherapistDetail);
        pnlTherapistDetail.setLayout(pnlTherapistDetailLayout);
        pnlTherapistDetailLayout.setHorizontalGroup(
            pnlTherapistDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnlTherapistDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        pnlTherapistDetailLayout.setVerticalGroup(
            pnlTherapistDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnlTherapistDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        tpnlMainTherapist.addTab("Settings", pnlTherapistDetail);

        javax.swing.GroupLayout pnlMainTherapistLayout = new javax.swing.GroupLayout(pnlMainTherapist);
        pnlMainTherapist.setLayout(pnlMainTherapistLayout);
        pnlMainTherapistLayout.setHorizontalGroup(
            pnlMainTherapistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpnlMainTherapist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainTherapistLayout.setVerticalGroup(
            pnlMainTherapistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainTherapistLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnlMainTherapist, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE))
        );

        add(pnlMainTherapist);
    }// </editor-fold>//GEN-END:initComponents

    // Hide Therapist Panel and go to Home Panel
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        parent.goBackHome();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Select the Appointments File from directory
    private void btnAppointmentPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentPathActionPerformed
        selectFile(evt.getActionCommand());
    }//GEN-LAST:event_btnAppointmentPathActionPerformed

    // Select the Adjudications File from directory
    private void btnAdjudicationsPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjudicationsPathActionPerformed
        selectFile(evt.getActionCommand());
    }//GEN-LAST:event_btnAdjudicationsPathActionPerformed

    // Select the Transactions File from directory
    private void btnTransactionsPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionsPathActionPerformed
        selectFile(evt.getActionCommand());
    }//GEN-LAST:event_btnTransactionsPathActionPerformed

    // Select Directory where to store reports
    private void btnReportPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportPathActionPerformed
        selectFile(evt.getActionCommand());
    }//GEN-LAST:event_btnReportPathActionPerformed

    // Save all parameters on Database
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            saveParameters();
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    // Sett all fields with database information
    private void setFields() {
        txtAppointmentPath.setText(settings.getAppointmentFile());
        txtAdjudicationsPath.setText(settings.getAdjudicationsFile());
        txtTransactionsPath.setText(settings.getTransactionsFile());
        txtReportPath.setText(settings.getReportsPath());
        chbTherapistHireDate.setSelected(settings.isTherapistHireDate());
        txtTherapistHireDate.setText(Integer.toString(settings.getTherapistHireDays()));
        chbTherapistProfLic.setSelected(settings.isTherapistProfLicense());
        txtTherapistProfLic.setText(Integer.toString(settings.getTherapistProfLicenseDays()));
        chbTherapistDriverLic.setSelected(settings.isTherapistDriverLic());
        txtTherapistDriverLic.setText(Integer.toString(settings.getTherapistDriverLicDays()));
        chbW4W9.setSelected(settings.isTherapistW4W9());
        txtW4W9.setText(Integer.toString(settings.getTherapistW4W9Days()));
        chbPhysicalExam.setSelected(settings.isTherapistPhysicalExam());
        txtPhysicalExam.setText(Integer.toString(settings.getTherapistPhysicalExamDays()));
        chbPatientBirthday.setSelected(settings.isPatientBirthday());
        txtPatientBirthday.setText(Integer.toString(settings.getPatientBirthdayDays()));
        chbPatientInsExp.setSelected(settings.isPatientInsExp());
        txtPatientInsExp.setText(Integer.toString(settings.getPatientInsExpDays()));
    }
        
    // Select File from directory
    private void selectFile(String command){
        File file;
        JFileChooser fc = new JFileChooser();
        
        // Set Selection mode to either File or Folder
        if (command.equalsIgnoreCase("Reports")){
                fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            } else {
                fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            }
        
        int response = fc.showDialog(this, command.equalsIgnoreCase("Reports")? "Select Reports Folder" : "Select " + command + " File");
        
        if (response == 0){
            // Select a File or a Directory
            if (command.equalsIgnoreCase("Reports")){
                file = fc.getCurrentDirectory();
            } else {
                file = fc.getSelectedFile();
            }
            
            switch (command){
                case "Appointments":
                    if (file.getAbsolutePath().endsWith(".csv")) txtAppointmentPath.setText(file.getAbsolutePath());
                    break;
                case "Adjudications":
                    if (file.getAbsolutePath().endsWith(".csv")) txtAdjudicationsPath.setText(file.getAbsolutePath());
                    break;
                case "Transactions":
                    if (file.getAbsolutePath().endsWith(".csv")) txtTransactionsPath.setText(file.getAbsolutePath());
                    break;
                case "Reports":
                    txtReportPath.setText(file.getAbsolutePath());
            }
        }
    }
    
    // Save all Patameters on Database
    private void saveParameters() throws SQLException{
        settings.setAppointmentFile(txtAppointmentPath.getText());
        settings.setAdjudicationsFile(txtAdjudicationsPath.getText());
        settings.setTransactionsFile(txtTransactionsPath.getText());
        settings.setReportsPath(txtReportPath.getText());
        settings.setIsTherapistHireDate(chbTherapistHireDate.isSelected());
        settings.setTherapistHireDays(Integer.valueOf(txtTherapistHireDate.getText()));
        settings.setIsTherapistProfLicense(chbTherapistProfLic.isSelected());
        settings.setTherapistProfLicenseDays(Integer.valueOf(txtTherapistProfLic.getText()));
        settings.setIsTherapistDriverLic(chbTherapistDriverLic.isSelected());
        settings.setTherapistDriverLicDays(Integer.valueOf(txtTherapistDriverLic.getText()));
        settings.setIsTherapistW4W9(chbW4W9.isSelected());
        settings.setTherapistW4W9Days(Integer.valueOf(txtW4W9.getText()));
        settings.setIsTherapistPhysicalExam(chbPhysicalExam.isSelected());
        settings.setTherapistPhysicalExamDays(Integer.valueOf(txtPhysicalExam.getText()));
        settings.setIsPatientBirthday(chbPatientBirthday.isSelected());
        settings.setPatientBirthdayDays(Integer.valueOf(txtPatientBirthday.getText()));
        settings.setIsPatientInsExp(chbPatientInsExp.isSelected());
        settings.setPatientInsExpDays(Integer.valueOf(txtPatientInsExp.getText()));
        
        int result = controller.updateApplicationSettings(settings);
        
        String message;
        if (result > 0){
            message = "Changes Saved Succesfully";
        } else {
            message = "Could not save changes";
        }
        
        JOptionPane.showMessageDialog(this, message, "Saving Settings", JOptionPane.INFORMATION_MESSAGE);
        setFields();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjudicationsPath;
    private javax.swing.JButton btnAppointmentPath;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReportPath;
    private javax.swing.JButton btnTransactionsPath;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chbPatientBirthday;
    private javax.swing.JCheckBox chbPatientInsExp;
    private javax.swing.JCheckBox chbPhysicalExam;
    private javax.swing.JCheckBox chbTherapistDriverLic;
    private javax.swing.JCheckBox chbTherapistHireDate;
    private javax.swing.JCheckBox chbTherapistProfLic;
    private javax.swing.JCheckBox chbW4W9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAdjudicationsPath;
    private javax.swing.JLabel lblAppointmentPath;
    private javax.swing.JLabel lblExternalTables;
    private javax.swing.JLabel lblNotificationsMain;
    private javax.swing.JLabel lblPatientBirthdayDaysBefore;
    private javax.swing.JLabel lblPatientInsExpDaysBefore;
    private javax.swing.JLabel lblPatientsNotifications;
    private javax.swing.JLabel lblPhysicalExamDaysBefore;
    private javax.swing.JLabel lblReportPath;
    private javax.swing.JLabel lblReportPathMain;
    private javax.swing.JLabel lblTherapistDriverLicDaysBefore;
    private javax.swing.JLabel lblTherapistHireDateDaysBefore;
    private javax.swing.JLabel lblTherapistNotifications;
    private javax.swing.JLabel lblTherapistProfLicDaysBefore;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTransactionsPath;
    private javax.swing.JLabel lblW4W9DaysBefore;
    private javax.swing.JPanel pnlMainTherapist;
    private javax.swing.JPanel pnlTherapistDetail;
    private javax.swing.JPanel pnlTherapistDetailInner;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JScrollPane spnlTherapistDetail;
    private javax.swing.JTabbedPane tpnlMainTherapist;
    private javax.swing.JTextField txtAdjudicationsPath;
    private javax.swing.JTextField txtAppointmentPath;
    private javax.swing.JTextField txtPatientBirthday;
    private javax.swing.JTextField txtPatientInsExp;
    private javax.swing.JTextField txtPhysicalExam;
    private javax.swing.JTextField txtReportPath;
    private javax.swing.JTextField txtTherapistDriverLic;
    private javax.swing.JTextField txtTherapistHireDate;
    private javax.swing.JTextField txtTherapistProfLic;
    private javax.swing.JTextField txtTransactionsPath;
    private javax.swing.JTextField txtW4W9;
    // End of variables declaration//GEN-END:variables

}
